package cli

import (
	"bytes"
	"os"
	"testing"
)

func TestAgentSkillMatchesGeneratedReference(t *testing.T) {
	var generated bytes.Buffer
	if err := WriteAgentSkill(&generated); err != nil {
		t.Fatalf("render agent skill: %v", err)
	}

	const path = "../../skills/using-mailbox/SKILL.md"
	committed, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read committed agent skill %q: %v", path, err)
	}
	if bytes.Equal(generated.Bytes(), committed) {
		return
	}

	first := 0
	for first < len(generated.Bytes()) && first < len(committed) && generated.Bytes()[first] == committed[first] {
		first++
	}
	start := first - 32
	if start < 0 {
		start = 0
	}
	generatedEnd := first + 32
	if generatedEnd > len(generated.Bytes()) {
		generatedEnd = len(generated.Bytes())
	}
	committedEnd := first + 32
	if committedEnd > len(committed) {
		committedEnd = len(committed)
	}
	t.Fatalf("agent skill diverged at byte %d; run `go generate ./...` to update %s:\ngenerated: %q\ncommitted: %q", first, path, generated.Bytes()[start:generatedEnd], committed[start:committedEnd])
}
